version: '3.8'
services:
  api:
    image: yiisoftware/yii2-php:8.2-apache
    environment:
      - VIRTUAL_HOST=api.app.local
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '127.0.0.1:8001:80'
    links:
      - redis

  db:
    image: mariadb:10
    volumes:
      - ./compose/db/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./compose/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./compose/db/data/db:/var/lib/mysql
    env_file:
      - ./compose/db/env
    ports:
      - 127.0.0.1:3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8082:8080

  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'